"""export_tree.py - freeze a TreeArrays into pure-Python and MQL5 if/else.

A decision tree is just a chain of `if x[f] <= thr` tests, so it transpiles to
zero-dependency code that runs in the RL hot loop, the live Python bot, and the
MQL5 EA -- with NO sklearn/pandas/numpy at evaluation time. We also emit golden
(input -> label) rows so a test can prove the frozen code matches the trainer and
the two surfaces can never silently drift (CLAUDE.md section 5).
"""
from __future__ import annotations
import numpy as np
from .tree_model import TreeArrays, LEAF
from .feature_spec import FEATURES


def _py_body(t: TreeArrays, node, indent):
    pad = "    " * indent
    if t.children_left[node] == LEAF:
        return f"{pad}return {t._leaf_label(node)}\n"
    f = int(t.feature[node]); thr = float(t.threshold[node])
    s = f"{pad}if x[{f}] <= {thr!r}:  # {t.feature_names[f]}\n"
    s += _py_body(t, int(t.children_left[node]), indent + 1)
    s += f"{pad}else:\n"
    s += _py_body(t, int(t.children_right[node]), indent + 1)
    return s


def export_python(t: TreeArrays, func_name="evaluate_tree") -> str:
    hdr = (f"def {func_name}(x):\n"
           f"    # Frozen decision tree -> +1 (long) / -1 (short) / 0 (flat).\n"
           f"    # x is a list[float] in FEATURES order; caller must ensure all finite.\n")
    return hdr + _py_body(t, 0, 1)


def _mql_body(t: TreeArrays, node, indent):
    pad = "   " * indent
    if t.children_left[node] == LEAF:
        return f"{pad}return({t._leaf_label(node)});\n"
    f = int(t.feature[node]); thr = float(t.threshold[node])
    s = f"{pad}if(x[{f}] <= {thr!r}) // {t.feature_names[f]}\n{pad}{{\n"
    s += _mql_body(t, int(t.children_left[node]), indent + 1)
    s += f"{pad}}}\n{pad}else\n{pad}{{\n"
    s += _mql_body(t, int(t.children_right[node]), indent + 1)
    s += f"{pad}}}\n"
    return s


def export_mql5(t: TreeArrays, func_name="EvaluateTree") -> str:
    hdr = (f"// Frozen decision tree -> +1 long / -1 short / 0 flat.\n"
           f"int {func_name}(const double &x[])\n{{\n")
    return hdr + _mql_body(t, 0, 1) + "}\n"


def golden_rows(t: TreeArrays, n=200, seed=0):
    rng = np.random.default_rng(seed)
    X = rng.normal(0, 3, size=(n, len(t.feature_names)))
    y = t.predict(X)
    return X.tolist(), y.tolist()


def write_python_module(t: TreeArrays, path, symbol="POOLED", meta=None):
    src = export_python(t)
    gx, gy = golden_rows(t, 64, seed=1)
    with open(path, "w") as f:
        f.write('"""AUTO-GENERATED frozen decision tree. Do not edit by hand."""\n')
        f.write(f"SYMBOL = {symbol!r}\n")
        f.write(f"FEATURES = {FEATURES!r}\n")
        f.write(f"N_FEATURES = {len(FEATURES)}\n")
        if meta:
            f.write(f"META = {meta!r}\n")
        f.write("\n" + src + "\n")
        f.write(f"GOLDEN_X = {gx!r}\n")
        f.write(f"GOLDEN_Y = {gy!r}\n")
    return path


# ---- scalar feature codegen (single source of truth for alpha + EA) ----
# Distances normalized by Bollinger-Band WIDTH dev1.0 (bb200 for the long SMA200
# distance, bb20 for the shorter ones). ATR appears ONLY in atrfrac (#10).
_FEAT_PATTERNS = [
    'g("rsi14_raw","{tf}") - 50.0',
    'g("rsi4_raw","{tf}") - 50.0',
    'g("cci30_raw","{tf}")',
    'g("cci100_raw","{tf}")',
    'div(g("sma_p1_s0","{tf}") - g("sma_p200_s0","{tf}"), g("bb200_dev1.0_upper","{tf}") - g("bb200_dev1.0_lower","{tf}"))',
    'div(g("sma_p1_s0","{tf}") - g("sma_p50_s0","{tf}"), g("bb20_dev1.0_upper","{tf}") - g("bb20_dev1.0_lower","{tf}"))',
    'div(g("sma_p1_s0","{tf}") - g("bb20_dev1.0_middle","{tf}"), g("bb20_dev1.0_upper","{tf}") - g("bb20_dev1.0_lower","{tf}"))',
    'div(g("sma_p1_s0","{tf}") - g("bb20_dev2.0_lower","{tf}"), g("bb20_dev2.0_upper","{tf}") - g("bb20_dev2.0_lower","{tf}"))',
    'div(g("sma_p1_s0","{tf}") - g("sma_p4_s3","{tf}"), g("bb20_dev1.0_upper","{tf}") - g("bb20_dev1.0_lower","{tf}"))',
    'div(g("atr14_raw","{tf}"), g("sma_p1_s0","{tf}"))',
    'div(g("sma_p1_s0","{tf}") - g("sma4_sh4_high","{tf}"), g("bb20_dev1.0_upper","{tf}") - g("bb20_dev1.0_lower","{tf}"))',
    'div(g("sma_p1_s0","{tf}") - g("sma4_sh4_low","{tf}"), g("bb20_dev1.0_upper","{tf}") - g("bb20_dev1.0_lower","{tf}"))',
]


def scalar_feature_lines(timeframes):
    lines = ["    x = ["]
    for tf in timeframes:
        lines.append(f"        # --- {tf} ---")
        for pat in _FEAT_PATTERNS:
            lines.append("        " + pat.format(tf=tf) + ",")
    lines.append("    ]")
    return "\n".join(lines)


_ALPHA_TMPL = '''"""decision_tree_ftmo_alpha.py - AUTO-GENERATED RL alpha (slot 16).

WHEN  : generated by ftmo_dt.train / export_tree on the frozen FTMO tree.
WHO   : decision-tree FTMO alpha (one tree, three surfaces).
WHY   : add a learned 3-class {{+1,-1,0}} setup detector to the RL pack without
        changing the locked observation (479 / 220). Reads only existing cached
        columns; derives scale-free features by plain arithmetic; evaluates a
        frozen if/else tree -- NO sklearn / pandas / TA-Lib in the hot loop.
WHERE : src/strategies/decision_tree_ftmo_alpha.py
HOW   : compute_signal(ctx) builds {n_feat} features in FEATURES order from
        ctx.ind(col, tf), abstains (0) if ANY is non-finite (warm-up), else runs
        the frozen tree -> +1 / -1 / 0.
DEPENDS_ON : src/strategies/base.BaseStrategy ; ctx.ind(col, tf).
USED_BY    : src/strategies/alpha_pack.register_all (slot 16).
CHANGE_NOTES-IRAC : keep FEATURES order frozen; regenerate this whole file when
        the tree is retrained (never hand-edit the if/else).
"""
from __future__ import annotations
import math

try:
    from src.strategies.base import BaseStrategy
    from config.constants import ALPHA_BUY, ALPHA_SELL, ALPHA_INACTIVE
except Exception:  # standalone / test shim
    class BaseStrategy:  # type: ignore
        name = "base"
        def reset(self): pass
        def signal(self, ctx):
            v = int(self.compute_signal(ctx))
            assert v in (-1, 0, 1)
            return v
    ALPHA_BUY, ALPHA_SELL, ALPHA_INACTIVE = 1, -1, 0

TIMEFRAMES = {timeframes!r}
FEATURES = {features!r}
N_FEATURES = {n_feat}


def div(a, b):
    if b == 0 or not math.isfinite(b) or a is None or not math.isfinite(a):
        return float("nan")
    return a / b


def _features(g):
{feature_lines}
    return x


{tree_src}

class DecisionTreeFtmoAlpha(BaseStrategy):
    name = "{alpha_name}"

    def compute_signal(self, ctx) -> int:
        g = lambda col, tf: ctx.ind(col, tf)
        x = _features(g)
        for v in x:
            if v is None or not math.isfinite(v):
                return ALPHA_INACTIVE          # warm-up / missing -> abstain
        s = evaluate_tree(x)
        return ALPHA_BUY if s > 0 else (ALPHA_SELL if s < 0 else ALPHA_INACTIVE)


GOLDEN_X = {golden_x!r}
GOLDEN_Y = {golden_y!r}
'''

_REGISTER_TMPL = '''"""register_decision_tree_ftmo_alpha.py - tiny register helper (slot 16)."""
from .decision_tree_ftmo_alpha import DecisionTreeFtmoAlpha


def register(registry):
    return registry.register(DecisionTreeFtmoAlpha())
'''


def write_rl_alpha(t: TreeArrays, path: str, timeframes, alpha_name="decision_tree_ftmo_5m_30m_4h"):
    from .feature_spec import FEATURES as _F
    feat_lines = scalar_feature_lines(timeframes)
    tree_src = export_python(t, "evaluate_tree")
    gx, gy = golden_rows(t, 64, seed=2)
    src = _ALPHA_TMPL.format(
        timeframes=tuple(timeframes), features=_F, n_feat=len(_F),
        feature_lines=feat_lines, tree_src=tree_src, alpha_name=alpha_name,
        golden_x=gx, golden_y=gy,
    )
    with open(path, "w") as f:
        f.write(src)
    return path


def write_register(path: str):
    with open(path, "w") as f:
        f.write(_REGISTER_TMPL)
    return path


# ---- MQL5 EA generation ------------------------------------------------------
_TF_ENUM = {"1m": "PERIOD_M1", "5m": "PERIOD_M5", "30m": "PERIOD_M30", "4h": "PERIOD_H4", "1d": "PERIOD_D1"}


def mql_feature_lines(timeframes):
    """MQL5 body filling x[] in FEATURES order (mirrors feature_spec). Distances
    use BB-width dev1.0: w20 = bb20 dev1 (= half the dev2 width); w200 = bb200 dev1.
    All reads at the last CLOSED bar (shift 1) + internal lags (fan +3, stacks +4)."""
    L = []
    for i, tf in enumerate(timeframes):
        b = i * 12
        L += [
            f"   // ---- {tf} ----",
            f"   double cl{i}=iClose(_Symbol,TFS[{i}],1);",
            f"   double r14_{i}=Buf(hRSI14[{i}],1), r4_{i}=Buf(hRSI4[{i}],1);",
            f"   double c30_{i}=Buf(hCCI30[{i}],1), c100_{i}=Buf(hCCI100[{i}],1);",
            f"   double s200_{i}=Buf(hSMA200[{i}],1), s50_{i}=Buf(hSMA50[{i}],1), s20_{i}=Buf(hSMA20[{i}],1);",
            f"   double s4_{i}=Buf(hSMA4c[{i}],4), atr_{i}=Buf(hATR[{i}],1);",
            f"   double bbu2_{i}=BufN(hBB20[{i}],1,1), bbl2_{i}=BufN(hBB20[{i}],2,1);",
            f"   double b2u_{i}=BufN(hBB200[{i}],1,1), b2l_{i}=BufN(hBB200[{i}],2,1);",
            f"   double sh_{i}=Buf(hSMA4h[{i}],5), slw_{i}=Buf(hSMA4l[{i}],5);",
            f"   double w20_{i}=(bbu2_{i}-bbl2_{i})/2.0, w200_{i}=(b2u_{i}-b2l_{i});",
            f"   if(cl{i}==EMPTY_VALUE||r14_{i}==EMPTY_VALUE||r4_{i}==EMPTY_VALUE||c30_{i}==EMPTY_VALUE||c100_{i}==EMPTY_VALUE||s200_{i}==EMPTY_VALUE||s50_{i}==EMPTY_VALUE||s20_{i}==EMPTY_VALUE||s4_{i}==EMPTY_VALUE||atr_{i}==EMPTY_VALUE||bbu2_{i}==EMPTY_VALUE||bbl2_{i}==EMPTY_VALUE||b2u_{i}==EMPTY_VALUE||b2l_{i}==EMPTY_VALUE||sh_{i}==EMPTY_VALUE||slw_{i}==EMPTY_VALUE) return(false);",
            f"   x[{b+0}]=r14_{i}-50.0;  x[{b+1}]=r4_{i}-50.0;  x[{b+2}]=c30_{i};  x[{b+3}]=c100_{i};",
            f"   x[{b+4}]=Div(cl{i}-s200_{i},w200_{i});  x[{b+5}]=Div(cl{i}-s50_{i},w20_{i});  x[{b+6}]=Div(cl{i}-s20_{i},w20_{i});",
            f"   x[{b+7}]=Div(cl{i}-bbl2_{i},bbu2_{i}-bbl2_{i});  x[{b+8}]=Div(cl{i}-s4_{i},w20_{i});  x[{b+9}]=Div(atr_{i},cl{i});",
            f"   x[{b+10}]=Div(cl{i}-sh_{i},w20_{i});  x[{b+11}]=Div(cl{i}-slw_{i},w20_{i});",
        ]
    return "\n".join(L)


_HANDLE_DECL = "int hRSI14[],hRSI4[],hCCI30[],hCCI100[],hSMA200[],hSMA50[],hSMA20[],hSMA4c[],hSMA4h[],hSMA4l[],hATR[],hBB20[],hBB200[];"


def _mql_init_handles(n):
    return f"""   int n={n};
   ArrayResize(hRSI14,n);ArrayResize(hRSI4,n);ArrayResize(hCCI30,n);ArrayResize(hCCI100,n);
   ArrayResize(hSMA200,n);ArrayResize(hSMA50,n);ArrayResize(hSMA20,n);ArrayResize(hSMA4c,n);
   ArrayResize(hSMA4h,n);ArrayResize(hSMA4l,n);ArrayResize(hATR,n);ArrayResize(hBB20,n);ArrayResize(hBB200,n);
   for(int i=0;i<n;i++){{
      hRSI14[i]=iRSI(_Symbol,TFS[i],14,PRICE_CLOSE);
      hRSI4[i] =iRSI(_Symbol,TFS[i],4,PRICE_CLOSE);
      hCCI30[i]=iCCI(_Symbol,TFS[i],30,PRICE_TYPICAL);
      hCCI100[i]=iCCI(_Symbol,TFS[i],100,PRICE_TYPICAL);
      hSMA200[i]=iMA(_Symbol,TFS[i],200,0,MODE_SMA,PRICE_CLOSE);
      hSMA50[i]=iMA(_Symbol,TFS[i],50,0,MODE_SMA,PRICE_CLOSE);
      hSMA20[i]=iMA(_Symbol,TFS[i],20,0,MODE_SMA,PRICE_CLOSE);
      hSMA4c[i]=iMA(_Symbol,TFS[i],4,0,MODE_SMA,PRICE_CLOSE);
      hSMA4h[i]=iMA(_Symbol,TFS[i],4,0,MODE_SMA,PRICE_HIGH);
      hSMA4l[i]=iMA(_Symbol,TFS[i],4,0,MODE_SMA,PRICE_LOW);
      hATR[i]=iATR(_Symbol,TFS[i],14);
      hBB20[i]=iBands(_Symbol,TFS[i],20,0,2.0,PRICE_CLOSE);
      hBB200[i]=iBands(_Symbol,TFS[i],200,0,1.0,PRICE_CLOSE);
   }}"""


def write_mql5_ea(t: TreeArrays, path: str, cfg, timeframes):
    tf_enum = ",".join(_TF_ENUM[tf] for tf in timeframes)
    sess = cfg.trade_sessions_utc[0]
    inputs = f"""input double InpRiskPctPerTrade = {cfg.risk_per_trade_pct*100:g};   // % equity risked / trade (0.01 = 0.01%)
input int    InpMaxTradesPerDay = {cfg.max_trades_per_day};
input double InpMaxDailyLossPct = {cfg.max_daily_loss_pct*100:g};
input double InpMaxTotalLossPct = {cfg.max_total_loss_pct*100:g};
input double InpDailyStopPct    = {cfg.daily_stop_pct*100:g};
input double InpDailyLockPct    = {cfg.daily_lock_profit_pct*100:g};
input double InpTotalStopPct    = {cfg.total_stop_pct*100:g};
input int    InpAtrPeriod       = {cfg.atr_period};
input double InpSlAtrMult       = {cfg.sl_atr_mult:g};
input double InpTpAtrMult       = {cfg.tp_atr_mult:g};
input int    InpMaxHoldBars     = {cfg.max_hold_bars};
input int    InpSessStartMin    = {sess[0]*60+sess[1]};   // UTC minutes
input int    InpSessEndMin      = {sess[2]*60+sess[3]};
input int    InpBrokerUtcOffset = {cfg.broker_utc_offset};
input bool   InpSwingMode       = {str(cfg.swing_mode).lower()};
input ulong  InpMagic           = 16016;
input int    InpSlippagePts     = {int(cfg.slippage_points)};"""
    ea = _EA_TEMPLATE
    ea = ea.replace("/*__INPUTS__*/", inputs)
    ea = ea.replace("/*__TF_ENUM__*/", tf_enum)
    ea = ea.replace("/*__NTF__*/", str(len(timeframes)))
    ea = ea.replace("/*__HANDLES_DECL__*/", _HANDLE_DECL)
    ea = ea.replace("/*__INIT_HANDLES__*/", _mql_init_handles(len(timeframes)))
    ea = ea.replace("/*__FEATURES__*/", mql_feature_lines(timeframes))
    ea = ea.replace("/*__EVALUATE_TREE__*/", export_mql5(t, "EvaluateTree"))
    ea = ea.replace("/*__NFEAT__*/", str(len(t.feature_names)))
    with open(path, "w") as f:
        f.write(ea)
    return path


_EA_TEMPLATE = r'''//+------------------------------------------------------------------+
//|  FtmoDecisionTree.mq5                                            |
//|  AUTO-GENERATED frozen decision tree + FTMO risk manager.        |
//|  One tree, identical to the Python backtest & RL alpha.          |
//|  Attach to ONE chart per symbol (M1). Tree is symbol-agnostic.   |
//+------------------------------------------------------------------+
#property strict
#include <Trade/Trade.mqh>

/*__INPUTS__*/

CTrade   trade;
ENUM_TIMEFRAMES TFS[] = { /*__TF_ENUM__*/ };
/*__HANDLES_DECL__*/

double   g_init_balance = 0.0;
double   g_day_start_eq = 0.0;
datetime g_cur_day      = 0;
int      g_trades_today = 0;
bool     g_day_blocked  = false;
bool     g_killed       = false;
datetime g_last_bar     = 0;

//------------------------------------------------------------------ helpers
double Buf(int h,int shift){ double t[]; ArraySetAsSeries(t,true);
   if(h==INVALID_HANDLE) return(EMPTY_VALUE);
   if(CopyBuffer(h,0,shift,1,t)!=1) return(EMPTY_VALUE); return(t[0]); }
double BufN(int h,int b,int shift){ double t[]; ArraySetAsSeries(t,true);
   if(h==INVALID_HANDLE) return(EMPTY_VALUE);
   if(CopyBuffer(h,b,shift,1,t)!=1) return(EMPTY_VALUE); return(t[0]); }
double Div(double a,double b){ if(b==0.0||!MathIsValidNumber(a)||!MathIsValidNumber(b)) return(EMPTY_VALUE); return(a/b); }

int UtcMinuteOfDay(){ datetime utc=TimeCurrent()-InpBrokerUtcOffset*3600; MqlDateTime s; TimeToStruct(utc,s); return(s.hour*60+s.min); }
datetime ServerDay(){ MqlDateTime s; TimeToStruct(TimeCurrent(),s); s.hour=0; s.min=0; s.sec=0; return(StructToTime(s)); }
bool InSession(int m){ return(m>=InpSessStartMin && m<InpSessEndMin); }

//------------------------------------------------------------------ the frozen tree
/*__EVALUATE_TREE__*/

//------------------------------------------------------------------ features (FEATURES order)
bool BuildFeatures(double &x[]){
   ArrayResize(x,/*__NFEAT__*/);
/*__FEATURES__*/
   for(int k=0;k<ArraySize(x);k++) if(x[k]==EMPTY_VALUE || !MathIsValidNumber(x[k])) return(false);
   return(true);
}

//------------------------------------------------------------------ position helpers
bool HasPosition(){ for(int i=PositionsTotal()-1;i>=0;i--){ ulong tk=PositionGetTicket(i);
   if(PositionSelectByTicket(tk) && PositionGetString(POSITION_SYMBOL)==_Symbol &&
      PositionGetInteger(POSITION_MAGIC)==(long)InpMagic) return(true);} return(false); }
void CloseMine(string why){ for(int i=PositionsTotal()-1;i>=0;i--){ ulong tk=PositionGetTicket(i);
   if(PositionSelectByTicket(tk) && PositionGetString(POSITION_SYMBOL)==_Symbol &&
      PositionGetInteger(POSITION_MAGIC)==(long)InpMagic){ trade.PositionClose(tk); } } }

double LotsFor(double atr){
   double eq=AccountInfoDouble(ACCOUNT_EQUITY);
   double risk_cash=InpRiskPctPerTrade/100.0*eq;
   double sl_dist=InpSlAtrMult*atr;
   double tick_val=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
   double tick_sz =SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
   if(sl_dist<=0||tick_val<=0||tick_sz<=0) return(0.0);
   double per_lot=sl_dist/tick_sz*tick_val;
   double lots=risk_cash/MathMax(per_lot,1e-9);
   double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   double vmin=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   double vmax=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
   lots=MathFloor(lots/step)*step; lots=MathMax(vmin,MathMin(vmax,lots));
   return(lots);
}

//------------------------------------------------------------------ lifecycle
int OnInit(){
/*__INIT_HANDLES__*/
   trade.SetExpertMagicNumber(InpMagic);
   trade.SetDeviationInPoints(InpSlippagePts);
   g_init_balance=AccountInfoDouble(ACCOUNT_BALANCE);
   g_day_start_eq=AccountInfoDouble(ACCOUNT_EQUITY);
   g_cur_day=ServerDay();
   return(INIT_SUCCEEDED);
}

void OnTick(){
   datetime bt=iTime(_Symbol,PERIOD_M1,0);
   if(bt==g_last_bar) { ManageOpen(); return; }   // act once per new M1 bar
   g_last_bar=bt;

   datetime day=ServerDay();
   if(day!=g_cur_day){ g_cur_day=day; g_day_start_eq=AccountInfoDouble(ACCOUNT_EQUITY);
                       g_trades_today=0; g_day_blocked=false; }

   double eq=AccountInfoDouble(ACCOUNT_EQUITY);
   double day_pl=(eq-g_day_start_eq)/MathMax(g_day_start_eq,1e-9);

   if(eq<=g_day_start_eq*(1.0-InpMaxDailyLossPct/100.0)){ CloseMine("daily_wall"); g_day_blocked=true; return; }
   if(eq<=g_init_balance*(1.0-InpMaxTotalLossPct/100.0)){ CloseMine("total_wall"); g_killed=true; return; }
   if(day_pl<=-InpDailyStopPct/100.0) g_day_blocked=true;
   if(day_pl>= InpDailyLockPct/100.0){ CloseMine("daily_lock"); g_day_blocked=true; }
   if(eq<=g_init_balance*(1.0-InpTotalStopPct/100.0)) g_killed=true;

   ManageOpen();
   if(g_killed||g_day_blocked) return;
   if(HasPosition()) return;
   if(g_trades_today>=InpMaxTradesPerDay) return;
   int mod=UtcMinuteOfDay();
   if(!InSession(mod)) return;

   double x[]; if(!BuildFeatures(x)) return;
   int s=EvaluateTree(x);
   if(s==0) return;

   double atr=Buf(hATR[0],1); if(atr==EMPTY_VALUE||atr<=0) return;
   double lots=LotsFor(atr); if(lots<=0) return;
   double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK), bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
   double slp=InpSlAtrMult*atr, tpp=InpTpAtrMult*atr;
   bool ok=false;
   if(s>0)  ok=trade.Buy (lots,_Symbol,ask, ask-slp, ask+tpp, "dt_ftmo");
   else     ok=trade.Sell(lots,_Symbol,bid, bid+slp, bid-tpp, "dt_ftmo");
   if(ok) g_trades_today++;
}

void ManageOpen(){
   if(!HasPosition()) return;
   int mod=UtcMinuteOfDay();
   bool near_roll=(mod>=1440-5);
   if(!InpSwingMode && (!InSession(mod)||near_roll)){ CloseMine("session_flat"); return; }
   for(int i=PositionsTotal()-1;i>=0;i--){ ulong tk=PositionGetTicket(i);
      if(PositionSelectByTicket(tk) && PositionGetString(POSITION_SYMBOL)==_Symbol &&
         PositionGetInteger(POSITION_MAGIC)==(long)InpMagic){
         datetime ot=(datetime)PositionGetInteger(POSITION_TIME);
         if((TimeCurrent()-ot)>=InpMaxHoldBars*60) trade.PositionClose(tk);
      }
   }
}
//+------------------------------------------------------------------+
'''
